### ISSUE TITLE
hello，这个项目还维护么？

### ISSUE THREAD

**Issue by mfyang** [purejoy/baziapp#1]
好像baziapp部署的，和这里发布的源代码有点脱节。

**Comment by purejoy** [comment]
16年之后这里就没怎么更新了。回头我看看把代码同步一下。

**Comment by mfyang** [comment]
留个联系，请你做个咨询项目?

**Comment by purejoy** [comment]
> 留个联系，请你做个咨询项目?
hansanbo AT Gmail.com

**Comment by mfyang** [comment]
email您了。 或者您加我微信 yangye0665
